name: Add to Project
permissions: {}
jobs:
  add-to-project:
    name: Add to project
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
    - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd
      with:
        project-url: https://github.com/orgs/fastapi/projects/2
        github-token: ${{ secrets.PROJECTS_TOKEN }}
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  pull_request_target: null
  issues:
    types:
    - opened
    - reopened
