name: Latest Changes
permissions: {}
jobs:
  latest-changes:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged
      == true
    timeout-minutes: 5
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        ref: ${{ github.event.repository.default_branch }}
        token: ${{ secrets.FASTAPI_LATEST_CHANGES }}
        persist-credentials: true
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled
        == 'true' }}
      with:
        limit-access-to-actor: true
    - uses: tiangolo/latest-changes@c9b73efbc8992ef1a401e4235ea307a8ca8a724b
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        latest_changes_file: docs/en/docs/release-notes.md
        latest_changes_header: '## Latest Changes'
        end_regex: '^## '
        debug_logs: true
        label_header_prefix: '### '
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  pull_request_target:
    branches:
    - master
    types:
    - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true
      debug_enabled:
        description: Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)
        required: false
        default: 'false'
