name: FastAPI People
permissions: {}
jobs:
  job:
    if: github.repository_owner == 'fastapi'
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: true
    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version-file: .python-version
    - name: Setup uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
      with:
        version: 0.11.18
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml
          uv.lock
    - name: Install Dependencies
      run: uv sync --locked --no-dev --group github-actions
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled
        == 'true' }}
      with:
        limit-access-to-actor: true
      env:
        GITHUB_TOKEN: ${{ secrets.FASTAPI_PEOPLE }}
    - name: FastAPI People Experts
      run: uv run ./scripts/people.py
      env:
        GITHUB_TOKEN: ${{ secrets.FASTAPI_PEOPLE }}
        SLEEP_INTERVAL: ${{ vars.PEOPLE_SLEEP_INTERVAL }}
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  schedule:
  - cron: 0 14 1 * *
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)
        required: false
        default: 'false'
